// src/components/ErrorBoundary.tsx
import * as React from 'react';

import { AppError } from '@/lib/error';

interface ErrorBoundaryState {
	error: AppError | Error | null;
	errorInfo: React.ErrorInfo | null;
}

interface Props {
	children: React.ReactNode;
	fallback?: React.ComponentType<{ error: Error | AppError; reset: () => void }>;
}

/**
 * Error boundary component that catches errors during rendering
 * Updated for React 19's new error handling approach
 */
class ErrorBoundary extends React.Component<Props, ErrorBoundaryState> {
	constructor(props: Props) {
		super(props);
		this.state = { error: null, errorInfo: null };
	}

	static getDerivedStateFromError(error: Error): ErrorBoundaryState {
		// React 19 no longer re-throws this error, just reports it to console.error
		return { error, errorInfo: null };
	}

	componentDidCatch(error: Error, errorInfo: React.ErrorInfo): void {
		// In React 19, componentDidCatch is still called, but the error is not re-thrown
		this.setState({ error, errorInfo });

		// No need to console.error here as React 19 already does this
		// with improved formatting for caught errors
	}

	reset = (): void => {
		this.setState({ error: null, errorInfo: null });
	};

	render(): React.ReactNode {
		if (this.state.error) {
			if (this.props.fallback) {
				const FallbackComponent = this.props.fallback;
				return <FallbackComponent error={this.state.error} reset={this.reset} />;
			}

			// Default error UI with your design system
			const errorMessage = this.state.error.message || 'An unexpected error occurred';
			const errorStack = this.state.error.stack;
			const componentStack = this.state.errorInfo?.componentStack;
			const errorCode = this.state.error instanceof AppError ? this.state.error.code : 'UNKNOWN_ERROR';

			return (
				<div className='w-full max-w-md mx-auto my-8 p-6 rounded-md bg-white border border-tertiary-black-4 shadow-md'>
					<div className='flex flex-col items-center text-center gap-4'>
						<div className='w-14 h-14 flex items-center justify-center rounded-full bg-primary-red-4'>
							<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='2' className='w-7 h-7 text-primary-red-2'>
								<circle cx='12' cy='12' r='10' />
								<line x1='12' y1='8' x2='12' y2='12' />
								<line x1='12' y1='16' x2='12.01' y2='16' />
							</svg>
						</div>

						<h2 style={{ fontFamily: 'var(--font-heading)' }} className='text-lg font-semibold text-tertiary-black-2'>
							{errorCode === 'UNAUTHORIZED' ? 'Authentication Required' : errorCode === 'FORBIDDEN' ? 'Access Denied' : 'Something Went Wrong'}
						</h2>

						<p style={{ fontFamily: 'var(--font-body)' }} className='text-tertiary-black-1'>
							{errorMessage}
						</p>

						<details className='w-full mt-2 text-left'>
							<summary className='text-sm text-primary-blue-1 hover:text-primary-blue-2 cursor-pointer transition-colors'>View technical details</summary>
							<pre className='mt-2 text-xs bg-tertiary-black-4 bg-opacity-20 p-2 rounded overflow-auto scrollbar-hide max-h-40'>
								{errorStack}
								{componentStack && (
									<>
										<br />
										<br />
										Component Stack:
										{componentStack}
									</>
								)}
							</pre>
						</details>

						<div className='flex gap-3 mt-4'>
							<button onClick={this.reset} className='px-4 py-2 rounded bg-primary-blue-1 text-white hover:bg-primary-blue-2 transition-colors' style={{ fontFamily: 'var(--font-body)' }}>
								Try Again
							</button>

							<button
								onClick={() => window.location.reload()}
								className='px-4 py-2 rounded border border-tertiary-black-3 hover:bg-tertiary-black-4 hover:bg-opacity-30 transition-colors'
								style={{ fontFamily: 'var(--font-body)' }}>
								Reload Page
							</button>
						</div>
					</div>
				</div>
			);
		}

		return this.props.children;
	}
}

export default ErrorBoundary;

// src/components/ErrorBoundary.svelte
<!-- ErrorBoundary.svelte -->
<script lang="ts">
  import type { Component } from "svelte";
  import { AppError } from "@/lib/error";

  // Props
  export let fallback:
    | ConstructorOfATypedSvelteComponent
    | Component<any, any, any>
    | null
    | undefined = undefined;

  // State
  let error: Error | AppError | null = null;
  let errorInfo: { componentStack?: string } | null = null;

  // Error handler function
  function handleError(event: Event) {
    event.preventDefault(); // Prevent default handling

    // Extract error from event
    const caughtError =
      event instanceof ErrorEvent
        ? event.error
        : event instanceof PromiseRejectionEvent
          ? event.reason
          : new Error("Unknown error");

    if (caughtError) {
      error = caughtError;
      errorInfo = { componentStack: new Error().stack };
    }

    return false;
  }

  // Reset function
  function reset() {
    error = null;
    errorInfo = null;
  }

  // Helper function to get error code
  function getErrorCode(err: Error | AppError): string {
    if (err instanceof AppError) {
      return err.code;
    }
    return "UNKNOWN_ERROR";
  }
</script>

<!-- Capture global errors -->
<svelte:window
  on:error|preventDefault={handleError}
  on:unhandledrejection|preventDefault={handleError}
/>

{#if error}
  {#if fallback}
    <svelte:component this={fallback} {error} {reset} />
  {:else}
    <!-- Default error UI -->
    <div
      class="w-full max-w-md mx-auto my-8 p-6 rounded-md bg-white border border-tertiary-black-4 shadow-md"
    >
      <div class="flex flex-col items-center text-center gap-4">
        <div
          class="w-14 h-14 flex items-center justify-center rounded-full bg-primary-red-4"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            class="w-7 h-7 text-primary-red-2"
          >
            <circle cx="12" cy="12" r="10" />
            <line x1="12" y1="8" x2="12" y2="12" />
            <line x1="12" y1="16" x2="12.01" y2="16" />
          </svg>
        </div>

        <h2
          style="font-family: var(--font-heading)"
          class="text-lg font-semibold text-tertiary-black-2"
        >
          {#if getErrorCode(error) === "UNAUTHORIZED"}
            Authentication Required
          {:else if getErrorCode(error) === "FORBIDDEN"}
            Access Denied
          {:else}
            Something Went Wrong
          {/if}
        </h2>

        <p style="font-family: var(--font-body)" class="text-tertiary-black-1">
          {error.message || "An unexpected error occurred"}
        </p>

        <details class="w-full mt-2 text-left">
          <summary
            class="text-sm text-primary-blue-1 hover:text-primary-blue-2 cursor-pointer transition-colors"
          >
            View technical details
          </summary>
          <pre
            class="mt-2 text-xs bg-tertiary-black-4 bg-opacity-20 p-2 rounded overflow-auto scrollbar-hide max-h-40">
            {error.stack}
            {#if errorInfo?.componentStack}
              {"\n\nComponent Stack:"}
              {errorInfo.componentStack}
            {/if}
          </pre>
        </details>

        <div class="flex gap-3 mt-4">
          <button
            onclick={reset}
            class="px-4 py-2 rounded bg-primary-blue-1 text-white hover:bg-primary-blue-2 transition-colors"
            style="font-family: var(--font-body)"
          >
            Try Again
          </button>

          <button
            onclick={() => window.location.reload()}
            class="px-4 py-2 rounded border border-tertiary-black-3 hover:bg-tertiary-black-4 hover:bg-opacity-30 transition-colors"
            style="font-family: var(--font-body)"
          >
            Reload Page
          </button>
        </div>
      </div>
    </div>
  {/if}
{:else}
  <slot />
{/if}
