// src/components/OurImpactStatsSvelte/Statistic.svelte
<script lang="ts">
	import type { IStatistic } from '@/types/impactStats';
	import AnimatedNumber from './AnimatedNumber.svelte';

	interface Props extends IStatistic {
		start: number;
		duration?: number;
		'aria-label'?: string;
	}

	let { value, unit, text, start }: Props = $props();
</script>

<div class="bg-transparent mt-2 w-max">
	<div class="flex flex-col items-center justify-between text-center">
		<p class="text-lg lg:text-xl font-bold text-tertiary-black-1 font-heading" aria-live="polite">
			{#if value}
				<AnimatedNumber {unit} {value} {start} aria-label={`${unit}${value} ${text}`} />
			{/if}
		</p>
		<p class="text-md font-semibold text-tertiary-black-2 max-w-[80%] mt-1 leading-relaxed">
			{text}
		</p>
	</div>
</div>

// src/components/OurImpactStats/Statistic.tsx
import { Card } from "@/components/ui/card";
import AnimatedNumber from "./AnimatedNumber";
import type { StatisticProps } from "./index.astro";

const Statistic: React.FC<StatisticProps> = ({
  value,
  unit,
  text,
  start,
  index,
}) => {
  return (
    <Card
      key={index}
      className="bg-transparent border-none shadow-none mt-2 w-max"
    >
      <div className="flex flex-col items-center justify-between text-center">
        <p
          className="text-xl lg:text-2xl font-bold text-tertiary-black-1 font-heading"
          aria-live="polite"
        >
          {value && (
            <AnimatedNumber
              unit={unit}
              value={value}
              start={start}
              aria-label={`${unit}${value} ${text}`}
            />
          )}
        </p>
        <p className="text-md font-semibold text-tertiary-black-2 max-w-[80%] mt-1 leading-relaxed">
          {text}
        </p>
      </div>
    </Card>
  );
};

export default Statistic;
